//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gab.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Gab.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string OperationTimeout {
            get {
                return ResourceManager.GetString("OperationTimeout", resourceCulture);
            }
        }
        
        public static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }
        
        public static string MeetingRoomsLabel {
            get {
                return ResourceManager.GetString("MeetingRoomsLabel", resourceCulture);
            }
        }
        
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        public static string TomorrowLabel {
            get {
                return ResourceManager.GetString("TomorrowLabel", resourceCulture);
            }
        }
        
        public static string FreeLabel {
            get {
                return ResourceManager.GetString("FreeLabel", resourceCulture);
            }
        }
        
        public static string BookedLabel {
            get {
                return ResourceManager.GetString("BookedLabel", resourceCulture);
            }
        }
        
        public static string BookLabel {
            get {
                return ResourceManager.GetString("BookLabel", resourceCulture);
            }
        }
        
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        public static string RoomItWillBeBusySoonMessage {
            get {
                return ResourceManager.GetString("RoomItWillBeBusySoonMessage", resourceCulture);
            }
        }
        
        public static string EndMeetingConfirmMessage {
            get {
                return ResourceManager.GetString("EndMeetingConfirmMessage", resourceCulture);
            }
        }
    }
}
